server:
  port: 8082
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: '@datasource.url@'
    username: '@datasource.username@'
    driver-class-name: '@datasource.driver@'
    password: '@datasource.password@'
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: '@datasource.platform@'
    hibernate:
      use-new-id-generator-mappings: true
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
security:
  oauth2:
    resource:
      user-info-uri: '@user.info.url@'


