import BaseState from './BaseState'

const BASE_PATH = `${CONTEXT_PATH}d/kpi`
export default {
  namespaced: true,
  state: {
    baseUrl: BASE_PATH
  },
  modules: {
    dayHotel: new BaseState({ url: `${BASE_PATH}/dayHotels` }),
    dayHotelPrice: new BaseState({ url: `${BASE_PATH}/dayHotelPrices` }),
    dayHotelScore: new BaseState({ url: `${BASE_PATH}/dayHotelScores` }),
    dayLifeIndex: new BaseState({ url: `${BASE_PATH}/dayLifeIndexs` }),
    dayScenic: new BaseState({ url: `${BASE_PATH}/dayScenics` }),
    dayScenicWeather: new BaseState({ url: `${BASE_PATH}/dayScenicWeathers` }),
    dayTeam: new BaseState({ url: `${BASE_PATH}/dayTeams` }),
    dayTeamTourist: new BaseState({ url: `${BASE_PATH}/dayTeamTourists` }),
    dayTourist: new BaseState({ url: `${BASE_PATH}/dayTourists` }),
    hourAqi: new BaseState({ url: `${BASE_PATH}/hourAqis` }),
    hourHumidity: new BaseState({ url: `${BASE_PATH}/hourHumiditys` }),
    hourPrecipitation: new BaseState({ url: `${BASE_PATH}/hourPrecipitations` }),
    hourPressure: new BaseState({ url: `${BASE_PATH}/hourPressures` }),
    hourScenic: new BaseState({ url: `${BASE_PATH}/hourScenics` }),
    hourScenicAqi: new BaseState({ url: `${BASE_PATH}/hourScenicAqis` }),
    hourScenicComfort: new BaseState({ url: `${BASE_PATH}/hourScenicComforts` }),
    hourScenicParking: new BaseState({ url: `${BASE_PATH}/hourScenicParkings` }),
    hourScenicSentiment: new BaseState({ url: `${BASE_PATH}/hourScenicSentiments` }),
    hourSentiment: new BaseState({ url: `${BASE_PATH}/hourSentiments` }),
    hourTemperature: new BaseState({ url: `${BASE_PATH}/hourTemperatures` }),
    hourWind: new BaseState({ url: `${BASE_PATH}/hourWinds` }),
    hourWeather: new BaseState({ url: `${BASE_PATH}/hourWeathers` }),
    monthCity: new BaseState({ url: `${BASE_PATH}/monthCitys` }),
    monthComplaint: new BaseState({ url: `${BASE_PATH}/monthComplaints` }),
    monthHotelCom: new BaseState({ url: `${BASE_PATH}/monthHotelComs` }),
    monthTourisHotelLocalIn: new BaseState({ url: `${BASE_PATH}/monthTourisHotelLocalIns` }),
    monthHotelType: new BaseState({ url: `${BASE_PATH}/monthHotelTypes` }),
    monthInRegion: new BaseState({ url: `${BASE_PATH}/monthInRegions` }),
    monthIncome: new BaseState({ url: `${BASE_PATH}/monthIncomes` }),
    monthRegion: new BaseState({ url: `${BASE_PATH}/monthRegions` }),
    monthRegionTouristConsume: new BaseState({ url: `${BASE_PATH}/monthRegionTouristConsumes` }),
    monthRouteRank: new BaseState({ url: `${BASE_PATH}/monthRouteRanks` }),
    monthScenic: new BaseState({ url: `${BASE_PATH}/monthScenics` }),
    monthSentimentKeyword: new BaseState({ url: `${BASE_PATH}/monthSentimentKeywords` }),
    monthSentimentType: new BaseState({ url: `${BASE_PATH}/monthSentimentTypes` }),
    monthTeamConsume: new BaseState({ url: `${BASE_PATH}/monthTeamConsumes` }),
    monthTeamIn: new BaseState({ url: `${BASE_PATH}/monthTeamIns` }),
    monthTeamRegion: new BaseState({ url: `${BASE_PATH}/monthTeamRegions` }),
    monthTeamStay: new BaseState({ url: `${BASE_PATH}/monthTeamStays` }),
    monthTeamTourist: new BaseState({ url: `${BASE_PATH}/monthTeamTourists` }),
    monthTeamType: new BaseState({ url: `${BASE_PATH}/monthTeamTypes` }),
    monthTourist: new BaseState({ url: `${BASE_PATH}/monthTourists` }),
    monthTouristAge: new BaseState({ url: `${BASE_PATH}/monthTouristAges` }),
    monthTouristCheckIn: new BaseState({ url: `${BASE_PATH}/monthTouristCheckIns` }),
    monthTouristGender: new BaseState({ url: `${BASE_PATH}/monthTouristGenders` }),
    monthTouristLocalOut: new BaseState({ url: `${BASE_PATH}/monthTouristLocalOuts` }),
    monthTouristOccupation: new BaseState({ url: `${BASE_PATH}/monthTouristOccupations` }),
    monthTouristPurpose: new BaseState({ url: `${BASE_PATH}/monthTouristPurposes` }),
    monthTouristStay: new BaseState({ url: `${BASE_PATH}/monthTouristStays` }),
    monthTouristTeamSingle: new BaseState({ url: `${BASE_PATH}/monthTouristTeamSingles` }),
    monthTouristVisit: new BaseState({ url: `${BASE_PATH}/monthTouristVisits` }),
    monthTravelAgencyRank: new BaseState({ url: `${BASE_PATH}/monthTravelAgencyRanks` }),
    nowDistrictResource: new BaseState({ url: `${BASE_PATH}/nowDistrictResources` }),
    nowResource: new BaseState({ url: `${BASE_PATH}/nowResources` }),
    weather: new BaseState({ url: `${BASE_PATH}/weathers` }),
    yearCognitionAtlas: new BaseState({ url: `${BASE_PATH}/yearCognitionAtlass` }),
    yearGuidedGender: new BaseState({ url: `${BASE_PATH}/yearGuidedGenders` }),
    nowGuide: new BaseState({ url: `${BASE_PATH}/nowGuides` }),
    yearIndustrys: new BaseState({ url: `${BASE_PATH}/yearIndustrys` }),
    yearCity: new BaseState({ url: `${BASE_PATH}/yearCitys` }),
    yearMedia: new BaseState({ url: `${BASE_PATH}/yearMedias` }),
    yearRegion: new BaseState({ url: `${BASE_PATH}/yearRegions` }),
    yearResource: new BaseState({ url: `${BASE_PATH}/yearResources` }),
    yearScenic: new BaseState({ url: `${BASE_PATH}/yearScenics` }),
    yearScenicCityCar: new BaseState({ url: `${BASE_PATH}/yearScenicCityCars` }),
    yearScenicComAcc: new BaseState({ url: `${BASE_PATH}/yearScenicComAccs` }),
    yearTeamRegion: new BaseState({ url: `${BASE_PATH}/yearTeamRegions` }),
    yearTeamStay: new BaseState({ url: `${BASE_PATH}/yearTeamStays` }),
    yearTeamGenderAge: new BaseState({ url: `${BASE_PATH}/yearTeamGenderAges` }),
    yearTourist: new BaseState({ url: `${BASE_PATH}/yearTourists` }),
    yearTouristIn: new BaseState({ url: `${BASE_PATH}/yearTouristIns` }),
    yearTouristAge: new BaseState({ url: `${BASE_PATH}/yearTouristAges` }),
    yearTouristConsume: new BaseState({ url: `${BASE_PATH}/yearTouristConsumes` }),
    yearTouristGender: new BaseState({ url: `${BASE_PATH}/yearTouristGenders` }),
    yearTouristHoliday: new BaseState({ url: `${BASE_PATH}/yearTouristHolidays` }),
    yearTouristHolidayType: new BaseState({ url: `${BASE_PATH}/yearTouristHolidayTypes` }),
    yearTouristHotel: new BaseState({ url: `${BASE_PATH}/yearTouristHotels` }),
    yearTouristScenic: new BaseState({ url: `${BASE_PATH}/yearTouristScenics` }),
    yearTouristStay: new BaseState({ url: `${BASE_PATH}/yearTouristStays` }),
    yearTouristTraffic: new BaseState({ url: `${BASE_PATH}/yearTouristTraffics` }),
    weatherForecast: new BaseState({ url: `${CONTEXT_PATH}d/gather/weatherForecastData` }),
    weatherLiveData: new BaseState({ url: `${CONTEXT_PATH}d/gather/weatherLiveData` })
  }
}
